services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - wikimedia-network

  broker:
    image: confluentinc/cp-server:7.3.2
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - wikimedia-network

  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@123
      MYSQL_DATABASE: wikimedia
    networks:
      - wikimedia-network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  wikimedia-data-processing:
    container_name: wikimedia-data-processing
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - wikimedia-network
    restart: on-failure
    depends_on:
      - broker
      - mysqldb

networks:
  wikimedia-network:
    driver: bridge

volumes:
  mysql-data: