services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@123
      MYSQL_DATABASE: wikimedia
    networks:
      - wikimedia-network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  wikimedia-network:

volumes:
  mysql-data: