spring:
  kafka:
    producer:
      bootstrap-servers: broker:29092  # Use service name 'broker' and Kafka port

kafka:
  topic:
    name: wikimedia_data

wikimedia:
  stream-url: https://stream.wikimedia.org/v2/stream/recentchange
